In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv('preprocessed_student_dataset.csv')

In [3]:
df

Age  Gender  Study_Hours_per_Week  Online_Courses_Completed  \
0    -1.582639     0.0              1.605127                  0.650559   
1     1.594887     0.0              0.220714                  1.628328   
2    -1.004907     0.0              1.528215                  0.161674   
3    -0.138309     0.0             -1.086788                 -1.630902   
4    -1.293773     0.0             -0.240757                  1.465366   
...        ...     ...                   ...                       ...   
9995 -1.004907     1.0              0.220714                 -0.653133   
9996 -0.138309     0.0             -0.856052                 -0.327210   
9997  0.728289     1.0             -0.317669                 -1.142018   
9998 -1.582639     1.0              1.066744                 -0.490172   
9999  0.150557     1.0             -1.471347                  1.628328   

      Participation_in_Discussions  Assignment_Completion_Rate (%)  \
0                                1                        1.708927   
1                                0                       -0.267263   
2                                0                       -1.016852   
3                                1                       -0.812418   
4                                1                       -1.084996   
...                            ...                             ...   
9995                             1                       -0.880563   
9996                             1                       -1.425719   
9997                             1                       -1.425719   
9998                             1                       -0.607985   
9999                             1                        0.823049   

      Exam_Score (%)  Attendance_Rate (%)  Use_of_Educational_Tech  \
0          -0.067365            -0.616001                        1   
1          -1.710558            -1.226232                        1   
2          -1.540573             0.265444                        1   
3          -0.010703            -1.022822                        1   
4          -0.407336             1.214692                        1   
...              ...                  ...                      ...   
9995       -0.690645             0.062033                        1   
9996        0.782562             0.740068                        1   
9997       -1.710558            -0.344787                        0   
9998       -1.427249             1.011282                        1   
9999       -1.710558             0.401051                        0   

      Self_Reported_Stress_Level  Time_Spent_on_Social_Media (hours/week)  \
0                              2                                -0.657989   
1                              1                                 1.447930   
2                              0                                -0.214638   
3                              0                                 1.004579   
4                              1                                 1.226255   
...                          ...                                      ...   
9995                           1                                 0.228714   
9996                           1                                -0.990503   
9997                           1                                 0.561228   
9998                           0                                -0.990503   
9999                           2                                 0.228714   

      Sleep_Hours_per_Night  Final_Grade  
0                  0.511151            2  
1                  0.511151            3  
2                  0.010366            3  
3                  1.512721            1  
4                  0.511151            2  
...                     ...          ...  
9995              -0.490419            2  
9996              -0.991204            1  
9997               0.511151            3  
9998               0.511151            3  
9999              -1.491988            3  

In [4]:
print(df.isnull().sum())

Age                                          0
Gender                                     406
Study_Hours_per_Week                         0
Online_Courses_Completed                     0
Participation_in_Discussions                 0
Assignment_Completion_Rate (%)               0
Exam_Score (%)                               0
Attendance_Rate (%)                          0
Use_of_Educational_Tech                      0
Self_Reported_Stress_Level                   0
Time_Spent_on_Social_Media (hours/week)      0
Sleep_Hours_per_Night                        0
Final_Grade                                  0
dtype: int64


In [5]:
# Fill missing Gender with mode
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)


In [6]:
print(df.isnull().sum())

Age                                        0
Gender                                     0
Study_Hours_per_Week                       0
Online_Courses_Completed                   0
Participation_in_Discussions               0
Assignment_Completion_Rate (%)             0
Exam_Score (%)                             0
Attendance_Rate (%)                        0
Use_of_Educational_Tech                    0
Self_Reported_Stress_Level                 0
Time_Spent_on_Social_Media (hours/week)    0
Sleep_Hours_per_Night                      0
Final_Grade                                0
dtype: int64


In [7]:
# Define independent (X) and target (y) variables
X = df.drop(['Final_Grade'], axis=1)  # Drop target and ID column
y = df['Final_Grade']

In [8]:
df["Final_Grade"].value_counts()

Final_Grade
0    2678
1    2455
2    2440
3    2427
Name: count, dtype: int64

In [9]:
# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
# Feature Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [11]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       533
           1       1.00      1.00      1.00       471
           2       1.00      1.00      1.00       495
           3       1.00      1.00      1.00       501

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

[[533   0   0   0]
 [  0 471   0   0]
 [  0   0 495   0]
 [  0   0   0 501]]


In [12]:
from sklearn.naive_bayes import BernoulliNB
classifier=BernoulliNB()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       0.55      0.98      0.71       533
           1       0.52      0.03      0.05       471
           2       0.46      0.49      0.48       495
           3       0.47      0.47      0.47       501

    accuracy                           0.51      2000
   macro avg       0.50      0.49      0.42      2000
weighted avg       0.50      0.51      0.43      2000

[[522  11   0   0]
 [423  12  20  16]
 [  0   0 244 251]
 [  0   0 267 234]]
